/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.ButtonGroup;

/**
 *
 * @author tbradford16
 */
public class DiceGUI extends javax.swing.JFrame {

    /**
     * Creates new form DiceGUI
     */
    private Login login = new Login();
    private DiceGame game = new DiceGame();

    public DiceGUI() {
        initComponents();
        groupButton();
    }
/**
 * @see groupButton() adds the radio buttons to a Button group
 */
    private void groupButton() {
        ButtonGroup bg1 = new ButtonGroup();

        bg1.add(O_RB);
        bg1.add(U_RB);
        bg1.add(E_RB);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        O_RB = new javax.swing.JRadioButton();
        E_RB = new javax.swing.JRadioButton();
        U_RB = new javax.swing.JRadioButton();
        bet_TF = new javax.swing.JTextField();
        Bet_B = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RT_TF = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Login_B = new javax.swing.JButton();
        Login_TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        O_RB.setText("Bet Over  7");

        E_RB.setText("Bet Equal to 7");

        U_RB.setText("Bet under 7 ");

        Bet_B.setText("Make Bet");
        Bet_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bet_BActionPerformed(evt);
            }
        });

        jLabel2.setText("Amount of money to bet");

        RT_TF.setText("Running Total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E_RB)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bet_TF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(U_RB, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(O_RB)
                            .addComponent(Bet_B)
                            .addComponent(RT_TF)))
                    .addComponent(jLabel2))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RT_TF)
                .addGap(12, 12, 12)
                .addComponent(O_RB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(E_RB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(U_RB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(bet_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bet_B)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Game Play", jPanel1);

        Login_B.setText("Login");
        Login_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_BActionPerformed(evt);
            }
        });

        jLabel1.setText("Login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Login_B, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(Login_TF))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(Login_B)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Game Play");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_BActionPerformed
        login.setLogin(Login_TF.getText());
        game.setTotal(login.getStartAmount(Login_TF.getText()));
        RT_TF.setText("Running Total:" + String.valueOf(game.getTotal()));
    }//GEN-LAST:event_Login_BActionPerformed

    private void Bet_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bet_BActionPerformed
       game.setBet(Double.parseDouble(bet_TF.getText()));
        if (O_RB.isSelected()) {
            game.makeBet(1);
             RT_TF.setText("Running Total:" + String.valueOf(game.getTotal()));
        }
       else if (E_RB.isSelected()) {
            game.makeBet(0);
            RT_TF.setText("Running Total:" + String.valueOf(game.getTotal()));
        }
       else if (U_RB.isSelected()) {
            game.makeBet(-1);
            RT_TF.setText("Running Total:" + String.valueOf(game.getTotal()));
        }
        login.setStartAmount(Login_TF.getText(),game.getTotal());
    }//GEN-LAST:event_Bet_BActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bet_B;
    private javax.swing.JRadioButton E_RB;
    private javax.swing.JButton Login_B;
    private javax.swing.JTextField Login_TF;
    private javax.swing.JRadioButton O_RB;
    private javax.swing.JLabel RT_TF;
    private javax.swing.JRadioButton U_RB;
    private javax.swing.JTextField bet_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
