/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pr2_6;

import java.awt.EventQueue;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Set;

/**
 *
 * @author tbradford16
 */
public class HomeworkTracker extends javax.swing.JFrame {
    
 public HashMap<String, HWT> Student;
    /**
     * Creates new form HomeworkTracker
     */
    public HomeworkTracker() {
        initComponents();
        Student = new HashMap<String, HWT>();
    }
    
//        public HomeworkTracker(String name,String Cname,double grade) {
//        initComponents();
//        Student = new HashMap<String, HWT>();
//        setGrade(name,Cname, grade);
//    }

    

   public void setGrade(String name,String Cname,double grade){
   this.Student.get(name).add(Cname, grade);
   }
    
    public String[] getStudent() {
        ArrayList<String> list = new ArrayList<String>();
        Set<String> keys = this.Student.keySet();

        String[] s = new String[keys.size()];
        int i = -1;
        for (String key : keys) {
            s[i + 1] = key;
            i++;
        }
        return s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainT = new javax.swing.JTextArea();
        Add_Name = new javax.swing.JTextField();
        findSButton = new javax.swing.JButton();
        findStudent = new javax.swing.JTextField();
        edit_info_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addButton.setText("Add Student");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        mainT.setColumns(20);
        mainT.setRows(5);
        jScrollPane1.setViewportView(mainT);

        Add_Name.setToolTipText("Students name goes here ^_^");

        findSButton.setText("Find Student");
        findSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findSButtonActionPerformed(evt);
            }
        });

        findStudent.setToolTipText("Students name goes here ^_^");

        edit_info_button.setText("Edit Info");
        edit_info_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_info_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Add_Name))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(findSButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(findStudent)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(edit_info_button)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(Add_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findSButton)
                    .addComponent(findStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_info_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Student.put(Add_Name.getText(), new HWT());
        mainT.setText(Student.get(Add_Name.getText()).printToScreen());
        Add_Name.setText("");
    }//GEN-LAST:event_addButtonActionPerformed

    private void findSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findSButtonActionPerformed
        mainT.setText(Student.get(findStudent.getText()).printToScreen());
    }//GEN-LAST:event_findSButtonActionPerformed

    private void edit_info_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_info_buttonActionPerformed
        // TODO add your handling code here: 
        EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                EditPopUp.setHomeworkTracker(HomeworkTracker.this);
                EditPopUp.display(getStudent());
            }
        });

    }//GEN-LAST:event_edit_info_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeworkTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeworkTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeworkTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeworkTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeworkTracker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Add_Name;
    private javax.swing.JButton addButton;
    private javax.swing.JButton edit_info_button;
    private javax.swing.JButton findSButton;
    private javax.swing.JTextField findStudent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mainT;
    // End of variables declaration//GEN-END:variables
}
